version: '2'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arqui
      MYSQL_USER: user
      MYSQL_PASSWORD: arquisoft
      MYSQL_DATABASE: backDev
      MYSQL_HOST: db
  web:
    build: .
    command: bash -c "sleep 120 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3001:3000"
    depends_on:
      - db
