# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e4616713402a22a05180a814bfc6cec4309e5fc14441285c866d207e086b527e1eee145c3ce611c43c92a2704d2d59dc75d42e7bed5098db63c51bc94cef9ca

test:
  secret_key_base: 2a652ad0bd23ffbfce3fac7bd85ccfe6123d50ef95423000bf7d597a334978bc7cf78739ea1ad43fc9348d79fb6737335f649434328f0ed3b231566efb92aa2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
